{
  viewer {
    repositories(
      first: 100
      privacy: PUBLIC
      orderBy: { field: PUSHED_AT, direction: DESC }
    ) {
      nodes {
        url
        name
        stargazerCount
        description
        isArchived
        isFork
        languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {
          nodes {
            name
            color
          }
        }
      }
    }

    repositoriesContributedTo(
      first: 100
      orderBy: { field: STARGAZERS, direction: DESC }
      contributionTypes: [COMMIT, PULL_REQUEST, REPOSITORY]
      privacy: PUBLIC
    ) {
      totalCount
      nodes {
        url
        name: nameWithOwner
        description
        languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {
          nodes {
            name
            color
          }
        }
      }
    }
  }
}
